spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 63921188128-ob0blt6mgouv6tku3j6iml04nqk13fdt.apps.googleusercontent.com
            client-secret: nQWKou1r5yoZ7ENz5lkLfGRQ
            scope: profile, email
          naver:
            client-id: CYY60Oq0TMbMuwJrKGoU
            client-secret: 9SOu8Tlnk0
            redirect_uri: http://localhost:8080/login/oauth2/code/naver
            authorization_grant_type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

---

